# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Alex Sorokoletov Notes
tagline:             Good luck with this code
url:                 http://sorokoletov.com
paginate:            5
baseurl:             ""
gems: [jekyll-paginate, jekyll-gist, jekyll-sitemap, jemoji]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Alex Sorokoletov
  url:               https://twitter.com/alexsorokoletov
  email:             alex@sorokoletov.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/alexsorokoletov/alexsorokoletov.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
  
excerpt_separator: '<!--more-->'
